import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  	return (
   		<div className={styles.container}>
    		<Head>
    		<title>My Portfolio</title>
        	<meta name="description" content="Generated by create next app" />
        	<link rel="icon" href="/favicon.ico" />
      		</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Hi! I'm Jennifer.
				</h1>

				<p className={styles.description}>
					Front-end web developer.
				</p>
				
			</main>
    	</div>
  )
}
