import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

import { SiAdobe, SiJavascript, SiMaildotru, SiNextdotjs, SiPhp, SiTypescript } from 'react-icons/si';
import { FaAngular, FaCss3Alt, FaGitAlt, FaGithub, FaHtml5, FaLinkedin, FaNodeJs, FaReact } from 'react-icons/fa';
import { TbApi } from 'react-icons/tb';
import { DiVisualstudio } from 'react-icons/di';
import { MdDevices } from 'react-icons/md';
import TypeWriter from 'typewriter-effect';

export default function Home() {
  	return (
   		<div className={styles.container}>
    		<Head>
    		<title>My Portfolio</title>
        	<meta name="description" content="Generated by create next app" />
        	<link rel="icon" href="/favicon.ico" />
      		</Head>

			<main className={styles.main}>

				{/* <Image src="/amazed.svg" width="500" height="500" className={styles.outline}></Image> */}

				<h1 className={styles.title}>
					Hi! I'm Jennifer.
				</h1>

				<div className={styles.description}>
					<span id={styles.preTypeWriterText}>Front-end web developer and </span>
					<TypeWriter
						options={{
							strings: ['plant mom.', 'bookworm.', 'Illustrator lover.', 'aspiring CSS guru.', 'occasional artist.'],
							autoStart: true,
							loop: true,
							pauseFor: 2500,
							delay: 100,
							deleteSpeed: 70,
							// wrapperClassName: 'typewriter'
						}}
					/>
				</div>

				<h2>Tools I've worked with</h2>
				
				<div className={styles.grid}>
					<div className={styles.card}>
						<FaHtml5 className={styles.icon} />
						<p>HTML5</p>
					</div>
					<div className={styles.card}>
						<FaCss3Alt className={styles.icon} />
						<p>CSS3</p>
					</div>
					<div className={styles.card}>
						<SiJavascript className={styles.icon} />
						<p>JavaScript</p>
					</div>
					<div className={styles.card}>
						<SiTypescript className={styles.icon} />
						<p>TypeScript</p>
					</div>
					<div className={styles.card}>
						<FaNodeJs className={styles.icon}/>
						<p>Node.js</p>
					</div>
					<div className={styles.card}>
						<FaAngular className={styles.icon}/>
						<p>Angular</p>
					</div>
					<div className={styles.card}>
						<FaReact className={styles.icon}/>
						<p>React</p>
					</div>
					<div className={styles.card}>
						<SiNextdotjs className={styles.icon}/>
						<p>Next.js</p>
					</div>
					<div className={styles.card}>
						<SiPhp className={styles.icon}/>
						<p>PHP</p>
					</div>
					<div className={styles.card}>
						<FaGitAlt className={styles.icon}/>
						<p>Git</p>
					</div>
					<div className={styles.card}>
						<FaGithub className={styles.icon}/>
						<p>GitHub</p>
					</div>
					<div className={styles.card}>
						<TbApi className={styles.icon}/>
						<p>RESTful APIs</p>
					</div>
					<div className={styles.card}>
						<MdDevices className={styles.icon}/>
						<p>Responsive Web Design</p>
					</div>
					<div className={styles.card}>
						<DiVisualstudio className={styles.icon}/>
						<p>VS Code</p>
					</div>
					<div className={styles.card}>
						<SiAdobe className={styles.icon}/>
						<p>Adobe Suite</p>
					</div>
					
					
				</div>

			</main>
			<footer className={styles.footer}>
				<p>Get in contact with me!</p>

				<div className={styles.footerLinks}>
					<a href="mailto:jennifer.svenssn@gmail.com"><SiMaildotru className={styles.footerIcon}></SiMaildotru></a>
					<a href="https://github.com/jennifersvensson1"><FaLinkedin className={styles.footerIcon}/></a>
					<a href="https://www.linkedin.com/in/jennifer-svensson-36172717b/"><FaGithub className={styles.footerIcon}/></a>
				</div>
			</footer>
    	</div>
  )
}
